# Generated by Django 5.0.14 on 2025-12-24 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_documento', models.CharField(choices=[('OFICIO', 'Oficio'), ('CERTIFICADO', 'Certificado')], max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado para Firma'), ('FIRMADO', 'Firmado y Finalizado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('numero_referencia', models.CharField(blank=True, help_text='Número de referencia humano-legible', max_length=50)),
                ('empresa_snapshot', models.JSONField(default=dict, help_text='Snapshot de datos de la empresa al momento de creación')),
                ('origen_consulta', models.CharField(blank=True, help_text='RUC o número de aviso consultado', max_length=100)),
                ('hash_seguridad', models.CharField(blank=True, help_text='SHA-256 del documento firmado', max_length=64)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Motivo del rechazo si aplica')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('firmante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas', to=settings.AUTH_USER_MODEL)),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
