# Generated by Django 5.0.14 on 2026-02-17 02:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_documento', models.CharField(choices=[('OFICIO', 'Oficio'), ('CERTIFICADO', 'Certificado')], max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Revisión'), ('APROBADO', 'Aprobado para Firma'), ('FIRMADO', 'Firmado y Finalizado'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20)),
                ('numero_referencia', models.CharField(blank=True, help_text='Número de referencia humano-legible', max_length=50)),
                ('empresa_snapshot', models.JSONField(default=list, help_text='Snapshot de datos de la empresa al momento de creación')),
                ('numero_carpetilla', models.CharField(blank=True, help_text='Número de carpetilla (solo para oficios)', max_length=100)),
                ('origen_consulta', models.CharField(blank=True, help_text='RUC o número de aviso consultado', max_length=100)),
                ('hash_seguridad', models.CharField(blank=True, help_text='SHA-256 del documento firmado', max_length=64)),
                ('archivo_pdf', models.FileField(blank=True, help_text='PDF original generado al crear el trámite', null=True, upload_to='pdfs/')),
                ('archivo_pdf_firmado', models.FileField(blank=True, help_text='PDF firmado externamente y subido por el director', null=True, upload_to='pdfs/firmados/')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Motivo del rechazo si aplica')),
                ('destinatario', models.CharField(blank=True, help_text='Nombre del destinatario del documento (ej: Señor LUIS ABREGO)', max_length=200)),
                ('proposito', models.TextField(blank=True, help_text='Propósito del trámite (ej: traspaso vehicular)')),
                ('fecha_solicitud', models.DateField(blank=True, help_text='Fecha en que el MICI recibió la solicitud', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('firmante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmas', to=settings.AUTH_USER_MODEL)),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trámite',
                'verbose_name_plural': 'Trámites',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaOficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('texto_pregunta', models.TextField()),
                ('texto_respuesta', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('respondida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='tramites.tramite')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
