# Generated by Django 5.0.14 on 2025-12-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='destinatario',
            field=models.CharField(blank=True, help_text='Nombre del destinatario del documento (ej: Señor LUIS ABREGO)', max_length=200),
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_solicitud',
            field=models.DateField(blank=True, help_text='Fecha en que el MICI recibió la solicitud', null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='proposito',
            field=models.TextField(blank=True, help_text='Propósito del trámite (ej: traspaso vehicular)'),
        ),
    ]
