# Generated by Django 5.0.14 on 2026-02-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_tramite_objetivo_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='cargo_destinatario',
            field=models.TextField(blank=True, help_text='Cargo del destinatario (ej: Fiscal Adjunta de la Fiscalía Anticorrupción...)'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='institucion_destinatario',
            field=models.CharField(blank=True, help_text='Institución del destinatario (ej: MINISTERIO PÚBLICO)', max_length=200),
        ),
        migrations.AddField(
            model_name='tramite',
            name='numero_oficio_externo',
            field=models.CharField(blank=True, help_text='Número de oficio externo (referencia del solicitante, ej: 7487/202500039050/sl)', max_length=200),
        ),
        migrations.AddField(
            model_name='tramite',
            name='titulo_destinatario',
            field=models.CharField(blank=True, help_text='Título del destinatario (ej: Licenciada, Señor)', max_length=100),
        ),
    ]
