# Generated by Django 5.0.14 on 2025-12-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0002_tramite_destinatario_tramite_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='archivo_pdf_firmado',
            field=models.FileField(blank=True, help_text='PDF firmado externamente y subido por el director', null=True, upload_to='pdfs/firmados/'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='PDF original generado al crear el trámite', null=True, upload_to='pdfs/'),
        ),
    ]
