# Generated by Django 5.0.14 on 2026-03-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0007_rename_revision_pdf_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='noconsta_snapshot',
            field=models.JSONField(default=list, help_text="Lista de entradas de 'No Consta' escritas manualmente por el fiscal"),
        ),
    ]
