# Generated by Django 5.0.14 on 2026-04-25 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0008_tramite_noconsta_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('OFICIO', 'Oficio'), ('CERTIFICADO', 'Certificado')], max_length=20)),
                ('anio', models.PositiveIntegerField()),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secuencias_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secuencia de Trámite',
                'verbose_name_plural': 'Secuencias de Trámites',
                'ordering': ['-anio', 'tipo_documento'],
                'unique_together': {('tipo_documento', 'anio')},
            },
        ),
    ]
