# Generated by Django 5.0.14 on 2026-04-25 22:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0010_seed_secuenciatramite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='plantilla_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot inmutable de la plantilla de membrete usada al generar el PDF'),
        ),
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_aplicable', models.CharField(choices=[('CERTIFICADO', 'Solo Certificados'), ('OFICIO', 'Solo Oficios'), ('AMBOS', 'Certificados y Oficios')], max_length=20)),
                ('archivo_word', models.FileField(upload_to='plantillas/word/')),
                ('imagen_header', models.ImageField(upload_to='plantillas/headers/')),
                ('imagen_footer', models.ImageField(blank=True, null=True, upload_to='plantillas/footers/')),
                ('margen_superior_cm', models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('margen_inferior_cm', models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('margen_izquierdo_cm', models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('margen_derecho_cm', models.DecimalField(decimal_places=2, default=Decimal('2.5'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('5.0'))])),
                ('activa', models.BooleanField(default=False)),
                ('preview_visto', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plantillas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='plantilladocumento',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('tipo_aplicable',), name='una_plantilla_activa_por_tipo'),
        ),
    ]
