# Generated by Django 5.0.14 on 2026-04-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0013_clamp_margen_izquierdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilladocumento',
            name='imagen_footer_alto_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='imagen_footer_ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='imagen_header_alto_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='imagen_header_ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
