# Generated by Django 5.0.14 on 2026-04-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0014_plantilladocumento_imagen_footer_alto_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilladocumento',
            name='imagen_marca_agua',
            field=models.ImageField(blank=True, null=True, upload_to='plantillas/watermarks/'),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='imagen_marca_agua_alto_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='plantilladocumento',
            name='imagen_marca_agua_ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
