# Generated by Django 5.0.14 on 2026-04-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0015_plantilladocumento_imagen_marca_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilladocumento',
            name='cuerpo_plantilla_html',
            field=models.TextField(blank=True, default='', help_text='HTML editable del cuerpo del documento. Soporta placeholders [[FECHA_EMISION]], [[DESTINATARIO]], [[LISTA_EMPRESAS]], etc.'),
        ),
    ]
