# Generated by Django 5.0.14 on 2026-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_consultasecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraevento',
            name='tipo_evento',
            field=models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('CONSULTA_API', 'Consulta a API Externa'), ('CREACION_TRAMITE', 'Creación de Trámite'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('APROBACION', 'Aprobación de Trámite'), ('RECHAZO', 'Rechazo de Trámite'), ('FIRMA', 'Firma de Documento'), ('DESCARGA', 'Descarga de Documento'), ('GESTION_USUARIO', 'Gestión de Usuario')], max_length=20),
        ),
    ]
