# Generated by Django 5.0.14 on 2026-02-17 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('CONSULTA_API', 'Consulta a API Externa'), ('CREACION_TRAMITE', 'Creación de Trámite'), ('CAMBIO_ESTADO', 'Cambio de Estado'), ('APROBACION', 'Aprobación de Trámite'), ('RECHAZO', 'Rechazo de Trámite'), ('FIRMA', 'Firma de Documento'), ('DESCARGA', 'Descarga de Documento')], max_length=20)),
                ('ip_origen', models.GenericIPAddressField(help_text='IP del cliente que realizó la acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del evento')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
            ],
            options={
                'verbose_name': 'Evento de Auditoría',
                'verbose_name_plural': 'Eventos de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
