# Generated by Django 5.0.14 on 2026-02-17 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraevento',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bitacoraevento',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='bitacoraevento',
            index=models.Index(fields=['-timestamp'], name='auditoria_b_timesta_ad5f42_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacoraevento',
            index=models.Index(fields=['tipo_evento'], name='auditoria_b_tipo_ev_35b47b_idx'),
        ),
        migrations.AddIndex(
            model_name='bitacoraevento',
            index=models.Index(fields=['actor'], name='auditoria_b_actor_i_22bc89_idx'),
        ),
    ]
