# Generated by Django 5.0.14 on 2026-03-15 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
        ('tramites', '0004_respuesta_solicitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaSecuencia',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('consulta', models.CharField(max_length=200)),
                ('resultados_encontrados', models.PositiveIntegerField(default=0)),
                ('resultados_detalle', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField()),
                ('tramite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_asociadas', to='tramites.tramite')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_secuencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta Secuencial',
                'verbose_name_plural': 'Consultas Secuenciales',
                'ordering': ['-timestamp'],
            },
        ),
    ]
