# Generated by Django 5.0.14 on 2026-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomici',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Obliga al usuario a cambiar su contraseña en el siguiente inicio de sesión.'),
        ),
    ]
