# Generated by Django 5.0.14 on 2026-02-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='objetivo_solicitud',
            field=models.TextField(blank=True, help_text='Objetivo de la solicitud (ej: autenticación de certificado de operación)'),
        ),
    ]
