# Generated by Django 5.0.14 on 2026-02-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0003_tramite_cargo_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='respuesta_solicitud',
            field=models.TextField(blank=True, help_text='Respuesta libre a la solicitud (llenada durante revisión)'),
        ),
    ]
