# Generated by Django 5.0.14 on 2026-03-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0004_respuesta_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='html_pdf_editado',
            field=models.TextField(blank=True, default='', help_text='HTML editado del PDF (si fue modificado)'),
        ),
    ]
