# Generated by Django 5.0.14 on 2026-03-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0005_html_pdf_editado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=models.CharField(
                choices=[
                    ('BORRADOR', 'Borrador'),
                    ('PENDIENTE', 'Pendiente de Revisión'),
                    ('REVISION_PDF', 'Revisión PDF'),
                    ('APROBADO', 'Listo para Firma'),
                    ('FIRMADO', 'Firmado y Finalizado'),
                    ('RECHAZADO', 'Rechazado'),
                ],
                default='BORRADOR',
                max_length=20,
            ),
        ),
    ]
