# Generated by Django 5.0.14 on 2026-03-17 13:05

from django.db import migrations, models


def forwards_rename_revision_pdf(apps, schema_editor):
    Tramite = apps.get_model('tramites', 'Tramite')
    Tramite.objects.filter(estado='REVISION_PDF').update(estado='EN_REVISION')


def backwards_rename_revision_pdf(apps, schema_editor):
    Tramite = apps.get_model('tramites', 'Tramite')
    Tramite.objects.filter(estado='EN_REVISION').update(estado='REVISION_PDF')


class Migration(migrations.Migration):

    dependencies = [
        ('tramites', '0006_alter_tramite_estado'),
    ]

    operations = [
        migrations.RunPython(
            forwards_rename_revision_pdf,
            backwards_rename_revision_pdf,
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=models.CharField(
                choices=[
                    ('BORRADOR', 'Borrador'),
                    ('PENDIENTE', 'Pendiente de Revisión'),
                    ('EN_REVISION', 'En revisión'),
                    ('APROBADO', 'Aprobado'),
                    ('FIRMADO', 'Firmado y Finalizado'),
                    ('RECHAZADO', 'Rechazado'),
                ],
                default='BORRADOR',
                max_length=20,
            ),
        ),
    ]
